# Generated by Django 6.0.1 on 2026-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_applicationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
