# Generated by Django 6.0.1 on 2026-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
