# Generated by Django 6.0.1 on 2026-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('template', models.TextField(help_text='Use {actor}, {target}, {details} placeholders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='testsession',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
