# Generated by Django 6.0.1 on 2026-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_audittemplate_testsession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsetting',
            name='test_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
