# Generated by Django 6.0.1 on 2026-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_applicationsetting_test_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsetting',
            name='test_start_time',
        ),
        migrations.AddField(
            model_name='testsession',
            name='discord_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
