# Generated by Django 6.0.1 on 2026-02-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_applicationsetting_test_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('dev', 'Developer'), ('police_chief', 'Police Chief'), ('deputy_chief', 'Deputy Chief'), ('academy_commander', 'Academy Commander'), ('deputy_commander', 'Deputy Commander'), ('trainer', 'Trainer'), ('cadet', 'Cadet')], default='cadet', max_length=20),
        ),
    ]
